POST /cars/specifications/504c7e03-b988-4a0b-a3f0-586fee1062bd HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTI3MjMyMDgsImV4cCI6MTY1MjgwOTYwOCwic3ViIjoiOTNlMmJjZDktOGE1OC00ZWM3LTgzYWQtOTM3YTFiYWM3NjA1In0.Imij-I37VC9kZ3eHLrmKpCopBuhI3bOoZY62j0X_ChU
Host: localhost:3333
Content-Length: 113

{
	"specifications_id": [
		"2031ff13-3c8b-4ff4-97e2-d336cc45acb1",
		"8d0dd6eb-73f5-4eb1-986b-81a11dec08e0"
	]
}