POST /rentals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTI3MjMyMDgsImV4cCI6MTY1MjgwOTYwOCwic3ViIjoiOTNlMmJjZDktOGE1OC00ZWM3LTgzYWQtOTM3YTFiYWM3NjA1In0.Imij-I37VC9kZ3eHLrmKpCopBuhI3bOoZY62j0X_ChU
Host: localhost:3333
Content-Length: 106

{
	"expected_return_date": "2022-05-17T17:49:32.939Z",
	"car_id": "5d350ff5-1961-4b6e-afab-592af2018568"
}