POST /rentals/devolution/2fa57452-416f-42f5-9656-15797de39963 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTI3MjMyMDgsImV4cCI6MTY1MjgwOTYwOCwic3ViIjoiOTNlMmJjZDktOGE1OC00ZWM3LTgzYWQtOTM3YTFiYWM3NjA1In0.Imij-I37VC9kZ3eHLrmKpCopBuhI3bOoZY62j0X_ChU
Host: localhost:3333

