POST /refresh-token HTTP/1.1
Content-Type: application/json
Host: localhost:3333
Content-Length: 243

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHJlbnR4LmNvbS5iciIsImlhdCI6MTY1Mjg4MTk0NCwiZXhwIjoxNjU1NDczOTQ0LCJzdWIiOiJmOWJiNmExZS02ZmYwLTQ4NTUtOWViNC1jNTEwMTRhZGEzMDQifQ.GrUEiA3ycZxqXTdTXGw8hTEyo1IANUf4lOsjzjO4_4s"
}